"use strict";
exports.__esModule = true;
var professional_1 = require("./professional");
var AlPacino = new professional_1.Professional("Al Pacino", 82, "male", 85, 1.70, "black", "brown", "white", false, "american", 1, "actor, director, productor, guionista");
var RoberDeNiro = new professional_1.Professional("Rober De Niro", 78, "male", 90, 1.72, "grey", "brown", "white", false, "american", 2, "actor, director, productor, guionista ");
var LeoDicaprio = new professional_1.Professional("Leonardo DiCaprio", 47, "male", 89, 1.83, "blond", "cyan", "white", false, "american", 1, "actor,productor de cine");
var QuentinTarantino = new professional_1.Professional("Quentin Tarantino", 59, "male", 85, 1.82, "brown", "brown", "white", false, "american", 1, "director, productor, guinista, actor");
AlPacino.printProfessional();
RoberDeNiro.printProfessional();
LeoDicaprio.printProfessional();
QuentinTarantino.printProfessional();
